controller_list:
  - name: scaled_pos_joint_traj_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]

  # - name: rg_controller 
  #   action_ns: "RGEffortController"
  #   type: GripperCommand
  #   # default: true
  #   # parallel: true
  #   # joints:
  #   #   - panda_finger_joint1
  #   #   - panda_finger_joint2
  #   joints: [rg2_gripper_joint]
