controller_list:
  - name: fake_ur3e_group_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_rg2_group_controller
    type: $(arg fake_execution_type)
    joints:
      - rg2_gripper_joint
initial:  # Define initial robot poses per group
  - group: ur3e_group
    pose: zeros
  - group: rg2_group
    pose: gripper_open